enable: true
MYSQL:
  Enable: false
  host: 'localhost'
  port: '3306'
  database: 'LobbyPresents'
  table_name: 'presents'
  username: 'root'
  password: '123'
Effect:
  distance: 5
  ticks: 40
  amount_canclaim: 8
  amount_claimed: 3
  canclaim: VILLAGER_HAPPY
  claimed: CRIT
Messages:
  found: "&aYou found a present! &e(&b%found%&e/&b%total%&e)"
  alreadyfound: "&cFound already!"
  completed: "&bMerry Christmas!! &c(&a%found%&f/&a%total%&c)"
  actionbar: "&b&lLobby Presents &c(&a%found%&f/&a%total%&c)"
  actionbar-completed: "&b&lLobby Presents &a&lCompleted!&f &c(&a%found%&f/&a%total%&c)"
Actionbar:
  enable: true
  world: 
    - world_name_here
  update: 10
Sounds: {}
Rewards:
  type: sequence
  sequence-rewards: {}