name: LobbyPresents
version: '4.5'
main: com.github.poompk1pk.lobbypresents.Main
softdepend: [PlaceholderAPI]
author: poompk
commands:
  lobbypresents:
    aliases: [lobbypresent, lps]
    description: help menu!